{"name": "test_mult[4-8-30]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 32 == 30\n  +32\n  -30", "trace": "self = <testcases.test_func.Test_Pytest object at 0x106661c88>, fixture_func = <pyCode.calc.Calculator object at 0x106661550>, a = 4, b = 8, result = 30\n\n    @pytest.mark.parametrize('a,b,result', test_data[2])\n    @allure.feature('乘法测试')\n    def test_mult(self, fixture_func, a, b, result):\n>       assert fixture_func.mult(a, b) == result\nE       assert 32 == 30\nE         +32\nE         -30\n\ntestcases/test_func.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "d5696c79-5905-4bd9-a6ee-48e74ce684de-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "4"}, {"name": "b", "value": "8"}, {"name": "result", "value": "30"}], "start": 1594373023561, "stop": 1594373023561, "uuid": "730db8c2-f089-48c9-9c0f-17e1598d3d0c", "historyId": "56844e06e015eacf8bbb7d6cef1d87e5", "testCaseId": "f23b8f69bb19ec69f89b4ceb1ecccfec", "fullName": "testcases.test_func.Test_Pytest#test_mult", "labels": [{"name": "feature", "value": "乘法测试"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "Test_Pytest"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "51782-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_func"}]}