{"name": "test_mult[2-8-14]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 16 == 14\n +  where 16 = <bound method Calculator.mult of <pyCode.calc.Calculator object at 0x107092d68>>(2, 8)\n +    where <bound method Calculator.mult of <pyCode.calc.Calculator object at 0x107092d68>> = <pyCode.calc.Calculator object at 0x107092d68>.mult", "trace": "self = <testcases.test_func.Test_Pytest object at 0x107092278>, cal_demo = <pyCode.calc.Calculator object at 0x107092d68>, a = 2, b = 8, result = 14\n\n    @pytest.mark.parametrize('a,b,result', [(3, 10, 30), (2, 8, 14), (4, 8, 32)])\n    def test_mult(self, cal_demo,a,b,result):\n>       assert cal_demo.mult(a, b) == result\nE       assert 16 == 14\nE        +  where 16 = <bound method Calculator.mult of <pyCode.calc.Calculator object at 0x107092d68>>(2, 8)\nE        +    where <bound method Calculator.mult of <pyCode.calc.Calculator object at 0x107092d68>> = <pyCode.calc.Calculator object at 0x107092d68>.mult\n\ntestcases/test_func.py:16: AssertionError"}, "attachments": [{"name": "stdout", "source": "32a98fdd-a82d-40af-8c6e-d17ebf54b3cd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "8"}, {"name": "result", "value": "14"}], "start": 1594353369420, "stop": 1594353369420, "uuid": "b3d166a0-c75b-4923-9e49-e8d42f7e38e3", "historyId": "ab20fb020a30ec47adfec0c5a0e9d658", "testCaseId": "f23b8f69bb19ec69f89b4ceb1ecccfec", "fullName": "testcases.test_func.Test_Pytest#test_mult", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "Test_Pytest"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "46427-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_func"}]}