{"name": "test_sub[14-8-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = <bound method Calculator.sub of <pyCode.calc.Calculator object at 0x107082518>>(14, 8)\n +    where <bound method Calculator.sub of <pyCode.calc.Calculator object at 0x107082518>> = <pyCode.calc.Calculator object at 0x107082518>.sub", "trace": "self = <testcases.test_func.Test_Pytest object at 0x107068d68>, cal_demo = <pyCode.calc.Calculator object at 0x107082518>, a = 14, b = 8, result = 9\n\n    @pytest.mark.parametrize('a,b,result', [(10, 1, 9), (12, 2, 10), (14, 8, 9)])\n    def test_sub(self, cal_demo, a, b, result):\n>       assert cal_demo.sub(a, b) == result\nE       assert 6 == 9\nE        +  where 6 = <bound method Calculator.sub of <pyCode.calc.Calculator object at 0x107082518>>(14, 8)\nE        +    where <bound method Calculator.sub of <pyCode.calc.Calculator object at 0x107082518>> = <pyCode.calc.Calculator object at 0x107082518>.sub\n\ntestcases/test_func.py:12: AssertionError"}, "attachments": [{"name": "stdout", "source": "4bf96a31-677c-43cc-a3e8-9865765b5772-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "14"}, {"name": "b", "value": "8"}, {"name": "result", "value": "9"}], "start": 1594353369406, "stop": 1594353369406, "uuid": "aa40acba-b5c4-4743-8c36-2da26ff9462d", "historyId": "51cb5cf5939c362e2505d0e166dc1ece", "testCaseId": "7cc8d68fa89e0983cb04154598068833", "fullName": "testcases.test_func.Test_Pytest#test_sub", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "Test_Pytest"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "46427-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_func"}]}